import type { Metadata } from "next";
import { Marcellus } from "next/font/google";
import "./globals.css";
import { Box } from "@mui/material";
import Navbar from "./components/Navbar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });


const marcellus = Marcellus({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-marcellus",
  display: "swap",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={marcellus.className}>
        <Box
          sx={{
            backgroundColor: "#0b0b0b",
            height: "100vh",
            display: "flex",
            flexDirection: "column",
          }}
        >
          <Navbar />
          {children}
        </Box>
      </body>
    </html>
  );
}